### ISSUE TITLE
On Fedora 21, python3-lxml is also required

### ISSUE THREAD

**Issue by j1mc** [projectmallard/pintail#10]
Encountered an error on 'pintail init' after doing a fresh install of pintail.

> [jwc@xml-goods pinbook]$ pintail init
> Traceback (most recent call last):
>  File "/usr/bin/pintail", line 5, in <module>
>    pkg_resources.run_script('pintail==0.1', 'pintail')
>  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 483, in run_script
>    self.require(requires)[0].run_script(script_name, ns)
>  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 1348, in run_script
>     exec(script_code, namespace, namespace)
>  File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/EGG-INFO/scripts/pintail", line 24, in <module>
>  File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/pintail/**init**.py", line 27, in <module>
> ImportError: No module named 'lxml'

After installing python3-lxml, 'pintail init' was able to complete successfully.

**Comment by amigadave** [comment]
This was fixed in https://github.com/projectmallard/pintail/commit/8a59d2220080446ea6876b7179c2a5959e4532b7

**Comment by j1mc** [comment]
Thanks, @amigadave and @shaunix!
