### ISSUE TITLE
[links site:subdirs] not working for docbook source

### ISSUE THREAD

**Issue by zoglesby** [projectmallard/pintail#19]
When using [links site:subdirs] with docbook sources, no links are generated. 

Examples:
https://pagure.io/docs-fp-o/blob/master/f/index.duck
https://pagure.io/docs-fp-o/blob/master/f/pintail.cfg

**Comment by bexelbie** [comment]
I believe this is a local problem and may be fixed by https://pagure.io/docs-fp-o/pull-request/24

**Comment by zoglesby** [comment]
bexelbie seems to be correct, with the latest version from pypy and that change this is working. Closing the issue.
