### ISSUE TITLE
Incorrect fsf adress in source files

### ISSUE THREAD

**Issue by williamjmorenor** [projectmallard/pintail#21]
Hi

I am working in the packaging of pintial in Fedora repos and find than the fsf adress is wrong in those source files:

pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/search.py
pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/site.py
pintail.noarch: E: incorrect-fsf-address /usr/bin/pintail
pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/pintail-atom.xsl
pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/docbook.py
pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/pintail-html.xsl
pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/ducktype.py
pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/mallard.py
pintail.noarch: E: incorrect-fsf-address /usr/share/licenses/pintail/COPYING
pintail.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/pintail/git.py

**Comment by dhanvi** [comment]
@williamjmorenor Pintail version has been updated to 0.3 and the licence issue has been fixed 
for example https://github.com/projectmallard/pintail/blob/master/pintail/git.py

I have even able to package it, ignoring the warnings here https://copr.fedorainfracloud.org/coprs/dhanvi/pintail/

**Comment by williamjmorenor** [comment]
I see it is fixed in https://github.com/projectmallard/pintail/commit/6f2daf7d7d886ddd9dbb41f85b2ad8660cf998d5

But I am packaging:
https://github.com/projectmallard/pintail/commit/d669691666eaf67112bb77f719826a0fdb8a8f40

So I can update the packagin to catch the update , thanks
