### ISSUE TITLE
Notes are not styled

### ISSUE THREAD

**Issue by kittykat** [projectmallard/pintail#29]
I have a ducktype document which looks roughly like this:

```
[list numbered]
* One
* Two:
  [list numbered]
  * Something
  * Something2

    $note(Just in case)
* Three
```

When I build the HTML with pintail, I would expect the note styling to be pretty, but it looks like the rest of the text.

I assume that I'm using $note() correctly as there are no errors during the build.

**Comment by shaunix** [comment]
```
[list numbered]
* One
* Two:
  [list numbered]
  * Something
  * Something2

    [note]
    Just in case
* Three
```

Using the inline $note syntax is causing an implicit paragraph to wrap the note. The parser doesn't complain because it's syntactically OK.
